/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILED = 'FORGET_PASSWORD_FAILED';

export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILED = 'UPDATE_ACCOUNT_FAILED';


export const UPDATE_ACCOUNT_FINANCIAL = 'UPDATE_ACCOUNT_FINANCIAL';
export const UPDATE_ACCOUNT_FINANCIAL_SUCCESS = 'UPDATE_ACCOUNT_FINANCIAL_SUCCESS';
export const UPDATE_ACCOUNT_FINANCIAL_FAILED = 'UPDATE_ACCOUNT_FINANCIAL_FAILED';

export const UPDATE_ACCOUNT_CATEGORY = 'UPDATE_ACCOUNT_CATEGORY';
export const UPDATE_ACCOUNT_CATEGORY_SUCCESS = 'UPDATE_ACCOUNT_CATEGORY_SUCCESS';
export const UPDATE_ACCOUNT_CATEGORY_FAILED = 'UPDATE_ACCOUNT_CATEGORY_FAILED';

export const GET_COMPANIES = 'GET_COMPANIES';
export const ADD_COMPANY = 'ADD_COMPANY';
export const ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS';
export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const CREATE_COLUMN = 'CREATE_COLUMN';
export const CREATE_COLUMN_SUCCESS = 'CREATE_COLUMN_SUCCESS';
export const SET_ACTIVE = 'SET_ACTIVE';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const DELETE_POLICY = 'DELETE_POLICY';
export const DELETE_POLICY_SUCCESS = 'DELETE_POLICY_SUCCESS';
export const DELETE_POLICY_FAILED = 'DELETE_POLICY_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

export const ADD_CLIENT = 'ADD_CLIENT';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILED = 'ADD_CLIENT_FAILED';

export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAILED = 'GET_CLIENTS_FAILED';

export const GET_CLIENTS_CATEGORY = 'GET_CLIENTS_CATEGORY';
export const GET_CLIENTS_CATEGORY_SUCCESS = 'GET_CLIENTS_CATEGORY_SUCCESS';
export const GET_CLIENTS_CATEGORY_FAILED = 'GET_CLIENTS_CATEGORY_FAILED';

export const GET_CLIENT = 'GET_CLIENT';
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS';
export const GET_CLIENT_FAILED = 'GET_CLIENT_FAILED';

export const DELETE_CLIENT = 'DELETE_CLIENT';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAILED = 'DELETE_CLIENT_FAILED';

export const GET_SETTING = 'GET_SETTING';
export const GET_SETTING_SUCCESS = 'GET_SETTING_SUCCESS';
export const GET_SETTING_FAILED = 'GET_SETTING_FAILED';

export const ADD_POLICY = 'ADD_POLICY';
export const ADD_POLICY_SUCCESS = 'ADD_POLICY_SUCCESS';
export const ADD_POLICY_FAILED = 'ADD_POLICY_FAILED';

export const GET_POLICY = 'GET_POLICY';
export const GET_POLICY_SUCCESS = 'GET_POLICY_SUCCESS';
export const GET_POLICY_FAILED = 'GET_POLICY_FAILED';

export const UPDATE_POLICY = 'UPDATE_POLICY';
export const UPDATE_POLICY_SUCCESS = 'UPDATE_POLICY_SUCCESS';
export const UPDATE_POLICY_FAILED = 'UPDATE_POLICY_FAILED';

export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAILED = 'UPDATE_CLIENT_FAILED';